export const samplePurchases = [
  {
    id: "sample-headset",
    productName: "Wireless Headset",
    merchant: "Example Electronics",
    purchaseDate: "2026-06-02",
    price: 129.99,
    returnWindowDays: 30,
    refundWindowDays: 14,
    warrantyMonths: 12,
    model: "HX-220",
    serial: "DEMO-HX220-001",
    source: "sample",
    hasReceipt: true,
    notes: "Box and accessories required for return.",
    status: "active",
    createdAt: "2026-06-02T00:00:00.000Z",
  },
  {
    id: "sample-phone-case",
    productName: "Phone Case",
    merchant: "Example Electronics",
    purchaseDate: "2026-06-02",
    price: 24.99,
    returnWindowDays: 30,
    refundWindowDays: 14,
    warrantyMonths: 3,
    model: "Case Flex 15",
    serial: "",
    source: "sample",
    hasReceipt: true,
    notes: "Bundled on the same receipt as Wireless Headset.",
    status: "active",
    createdAt: "2026-06-02T00:00:00.000Z",
  },
  {
    id: "sample-coffee-maker",
    productName: "Coffee Maker",
    merchant: "Kitchen Corner",
    purchaseDate: "2026-05-14",
    price: 84.5,
    returnWindowDays: 60,
    refundWindowDays: 30,
    warrantyMonths: 24,
    model: "BrewHome C2",
    serial: "DEMO-BHC2-4421",
    source: "sample",
    hasReceipt: false,
    notes: "Find PDF receipt before warranty claim.",
    status: "active",
    createdAt: "2026-06-02T00:00:00.000Z",
  },
];
